# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kendalltaudist <- function(V) {
    .Call('_GSReg_kendalltaudist', PACKAGE = 'GSReg', V)
}

kendalltaudistFromTemp <- function(V, T) {
    .Call('_GSReg_kendalltaudistFromTemp', PACKAGE = 'GSReg', V, T)
}

kendalltaudistRestricted <- function(V, R) {
    .Call('_GSReg_kendalltaudistRestricted', PACKAGE = 'GSReg', V, R)
}

Nij <- function(V) {
    .Call('_GSReg_Nij', PACKAGE = 'GSReg', V)
}

